# Uptime Monitor Configuration

settings:
  title: "Moitr 's Status Page"
  callback_url: ""
  callback_secret: ""
  # If true, only send notifications when status changes to DOWN.
  # DEGRADED or UP (recovery) events will NOT trigger notifications.
  notification_on_down_only: true
  summary_exclusion: []
  tags:
    - id: "eopf"
      label: "EdgeOne Page Function"
      color: "#2563EB"
    - id: "eopage"
      label: "EdgeOne Page"
      color: "#2563EB"
    - id: "esa"
      label: "ESA CDN"
      color: "#EC2626"
    - id: "esapage"
      label: "ESA Page"
      color: "#EC2626"
    - id: "eo"
      label: "EdgeOne CDN"
      color: "#2563EB"
    - id: "cf"
      label: "Cloudflare CDN"
      color: "#D97706"
    - id: "cfw"
      label: "Cloudflare Worker"
      color: "#D97706"
    - id: "cfp"
      label: "Cloudflare Page"
      color: "#D97706"
    - id: "vercel"
      label: "Vercel Page"
      color: "#000000"
    - id: "vf"
      label: "Vercel Function"
      color: "#000000"
    - id: "self"
      label: "SelfHosted"
      color: "#4B5563"


groups:
  - id: "public_services"
    name: "Public Services"
    monitors:
      - id: "blog"
        name: "Blog"
        tags: [eo]
        type: "http"
        url: "https://moitr.ren/"
        method: "HEAD"
        timeout: 60000
        expected_latency: 5000
        grace_period: 3
        display:
          public_link: true
        validation:
          status: [200, 201, 204]

      - id: "dotme"
        name: "DotMe"
        tags: [eopage]
        type: "http"
        url: "https://moitr.cc/"
        method: "HEAD"
        timeout: 60000
        expected_latency: 5000
        grace_period: 3
        display:
          public_link: true
        validation:
          status: 200

  - id: "private_service"
    name: "Private Service"
    monitors:
      - id: "blog_backend_api"
        name: "Blog Backend API"
        tags: [eo]
        type: "http"
        url: "http://mx-server.moitr.ren/proxy/qaqdmin"
        method: "HEAD"
        timeout: 60000
        expected_latency: 5000
        grace_period: 3
        display:
          public_link: false
        validation:
          status: 200

      - id: "oss"
        name: "OSS"
        tags: [eo]
        type: "http"
        url: "https://oss.moitr.ren/test_ping.txt"
        method: "HEAD"
        timeout: 60000
        expected_latency: 5000
        grace_period: 3
        display:
          public_link: false
        validation:
          status: 200
